# Generated by Django 4.1 on 2022-08-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinesiologo',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/kinesiologo/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/paciente/', verbose_name='Foto de perfil'),
        ),
    ]
