# Generated by Django 4.1.1 on 2022-09-13 21:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_kinesiologo_profile_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre Categoría')),
                ('descripcion', models.TextField(blank=True, max_length=500, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre semana')),
            ],
        ),
        migrations.CreateModel(
            name='Grabacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre categoria')),
                ('video', models.FileField(null=True, upload_to='videos/pomo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre Ejercicio')),
                ('video', models.FileField(null=True, upload_to='videos/pomo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('detalle', models.TextField()),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.categoria')),
                ('kinesiologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.kinesiologo')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagina.ejercicio'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='kinesiologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.kinesiologo'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.paciente'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.semana'),
        ),
    ]
