# Generated by Django 4.1.1 on 2022-10-04 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_kinesiologo_profile_pic_and_more'),
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='kinesiologo',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='paciente',
        ),
        migrations.AddField(
            model_name='semana',
            name='kinesiologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.kinesiologo'),
        ),
        migrations.AddField(
            model_name='semana',
            name='paciente',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='users.paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semana',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre semana'),
        ),
    ]
