# Generated by Django 4.1.1 on 2022-10-31 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_ejercicio_video_thumbnail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actividad',
            new_name='Rutina',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='actividad',
            new_name='rutina',
        ),
        migrations.RenameField(
            model_name='grabacion',
            old_name='actividad',
            new_name='rutina',
        ),
    ]
