# Generated by Django 4.1.1 on 2022-10-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_rename_actividad_rutina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semana',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
