# Generated by Django 4.1.1 on 2022-11-30 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_semana_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.ejercicio'),
        ),
    ]
