# Generated by Django 4.1.1 on 2022-11-30 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_remove_grabacion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grabacion',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='grabacion',
            name='rutina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.rutina'),
        ),
    ]
