# Generated by Django 4.1.1 on 2022-11-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_alter_grabacion_date_uploaded_alter_grabacion_rutina'),
    ]

    operations = [
        migrations.AddField(
            model_name='grabacion',
            name='video_thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
