# Generated by Django 4.1.1 on 2022-11-30 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_grabacion_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='nota',
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.rutina')),
            ],
        ),
    ]
