# Generated by Django 4.1.1 on 2022-11-30 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0010_remove_feedback_nota_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='rutina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.rutina'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rutina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.rutina'),
        ),
    ]
